name: 'Scoop Action'
description: 'Installs Scoop package manager on Windows.'

inputs:
  scoop_version:
    description: 'Version of Scoop to install'
    required: false
    default: 'latest'

runs:
  using: 'powershell'
  main: 'install.ps1'
