name: 'Scoop Action'
description: 'Installs Scoop package manager on Windows.'

inputs:
  bucket_add:
    description: 'Comma-separated list of additional buckets to add'
    required: false
    default: 'main,extras'

runs:
  using: 'composite'
  steps:
    - name: Set execution policy to allow script running
      shell: pwsh
      run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

    - name: Install Scoop
      shell: pwsh
      run: |
        Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        $env:PATH += ";$env:USERPROFILE\scoop\shims"

    - name: Add buckets
      shell: pwsh
      run: |
        $buckets = '${{ inputs.bucket_add }}'.Split(',')
        foreach ($name in $buckets) {
          scoop bucket add $name
        }

    - name: Verify Scoop installation
      shell: pwsh
      run: scoop --version